services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: timecapsule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: freeMaker13#1cv
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d timecapsule" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: timecapsule-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://timecapsule-database-1.cuhsmymyg00w.us-east-1.rds.amazonaws.com:5432/timecapsule
      DB_USER: postgres
      DB_PASSWORD: freeMaker13#1cv
    depends_on:
      db:
        condition: service_healthy